/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../jni/jni.h"
/* Header for class com_oblivion_jni_text_MainActivity */

#ifndef _Included_com_oblivion_jni_text_MainActivity
#define _Included_com_oblivion_jni_text_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oblivion_jni_text_MainActivity
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oblivion_jni_1text_MainActivity_getStringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
